### ISSUE TITLE
WithDistributedPubSub throws NullReferenceException

### ISSUE THREAD

**Issue by jblackburn21** [akkadotnet/Akka.Hosting#55]
**Version Information**
Version of Akka.NET? 1.4.28
Which Akka.NET Modules? Akka.Cluster.Hosting 0.3.0

**Describe the bug**
I'm trying to configure DistributedPubSub using WithDistributedPubSub, but getting System.NullReferenceException

**To Reproduce**
1. Use WithDistributedPubSub("pub-sub-host") extension method on builder

**Expected behavior**

Configure DistributedPubSub with the role

**Actual behavior**
What actually happened and how did it differ from your expectations?

Getting the following exception

```csharp
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Akka.Configuration.Config.Contains(Config other)
   at Akka.Configuration.Config.WithFallback(Config fallback)
   at Akka.Configuration.Config.GetConfig(String path)
   at Akka.Configuration.Config.GetConfig(String path)
   at Akka.Configuration.Config.GetConfig(String path)
   at Akka.Configuration.Config.GetConfig(String path)
   at Akka.Configuration.Config.GetConfig(String path)
   at Akka.Configuration.Config.GetConfig(String path)
   at Akka.Configuration.Config.GetConfig(String path)
   at Akka.Configuration.Config.GetConfig(String path)
   at Akka.Configuration.Config.GetConfig(String path)
   at Akka.Cluster.Tools.PublishSubscribe.DistributedPubSubSettings.Create(ActorSystem system)
   at Akka.Cluster.Tools.PublishSubscribe.DistributedPubSub..ctor(ExtendedActorSystem system)
   at Akka.Cluster.Tools.PublishSubscribe.DistributedPubSubExtensionProvider.CreateExtension(ExtendedActorSystem system)
   at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.CreateExtension(ExtendedActorSystem system)
   at Akka.Actor.Internal.ActorSystemImpl.<>c__DisplayClass61_0.<RegisterExtension>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Akka.Actor.Internal.ActorSystemImpl.TryGetExtension(Type extensionType, Object& extension)
   at Akka.Actor.Internal.ActorSystemImpl.GetExtension(IExtensionId extensionId)
   at Akka.Actor.ExtensionIdProvider`1.Get(ActorSystem system)
   at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.Get(ActorSystem system)
   at Akka.Actor.Internal.ActorSystemImpl.RegisterExtension(IExtensionId extension)
   at Akka.Actor.ActorSystemWithExtensions.WithExtension[T,TI](ActorSystem system)
   at Akka.Cluster.Tools.PublishSubscribe.DistributedPubSub.Get(ActorSystem system)
   at Akka.Cluster.Tools.Client.ClusterClientReceptionist.get_PubSubMediator()
   at Akka.Cluster.Tools.Client.ClusterClientReceptionist.CreateReceptionist()
   at Akka.Cluster.Tools.Client.ClusterClientReceptionist..ctor(ExtendedActorSystem system)
   at Akka.Cluster.Tools.Client.ClusterClientReceptionistExtensionProvider.CreateExtension(ExtendedActorSystem system)
   at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.CreateExtension(ExtendedActorSystem system)
   at Akka.Actor.Internal.ActorSystemImpl.<>c__DisplayClass61_0.<RegisterExtension>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Akka.Actor.Internal.ActorSystemImpl.TryGetExtension(Type extensionType, Object& extension)
   at Akka.Actor.Internal.ActorSystemImpl.GetExtension(IExtensionId extensionId)
   at Akka.Actor.ExtensionIdProvider`1.Get(ActorSystem system)
   at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.Get(ActorSystem system)
   at Akka.Actor.Internal.ActorSystemImpl.RegisterExtension(IExtensionId extension)
   at Akka.Actor.Internal.ActorSystemImpl.ConfigureExtensions(IEnumerable`1 extensionIdProviders)
   at Akka.Actor.Internal.ActorSystemImpl.Start()
   at Akka.Actor.ActorSystem.CreateAndStartSystem(String name, Config withFallback, ActorSystemSetup setup)
   at Akka.Actor.ActorSystem.Create(String name, ActorSystemSetup setup)
   at Akka.Hosting.AkkaConfigurationBuilder.<>c.<ActorSystemFactory>b__28_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.<Main>$(String[] args) in /Users/jblackburn/repos/signify/architecture/architecture.templates/templates/akkaclusterservice/src/akkacluster.Service/Program.cs:line 25
   at Program.<Main>(String[] args)
```

**Environment**
Docker, dotnet 6 

** Additional Info**
It looks like the hocon config is incorrect `akka.cluster.pub-sub`, should it be?

```csharp
middle.AddHocon($"akka.cluster.pub-sub.role = \"{role}\"", HoconAddMode.Prepend);
```

**Comment by Aaronontheweb** [comment]
This is fixed in 0.3.1, which we are releasing now: https://github.com/akkadotnet/Akka.Hosting/pull/59

**Comment by jblackburn21** [comment]
Let me know if you want a new issue, but I tried using this, and I think the order of applying the hocon isn't correct. I'm getting this error in lighthouse, which means that it isn't honoring the role

```
---> System.Runtime.Serialization.SerializationException: Cannot find serializer with id [9] (manifest [A]). The most probable reason is that the configuration entry 'akka.actor.serializers' is not in sync between the two systems. Could not find any internal Akka.NET serializer with Id [9]. Please create an issue in our GitHub at [https://github.com/akkadotnet/akka.net].
```

**Comment by Arkatufus** [comment]
@jblackburn21 we can re-open this, yes, it is still a problem. We'll fix it as soon as possible.
